### ISSUE TITLE
Does it support Keyframes?

### ISSUE THREAD

**Issue by n4j1Br4ch1D** [mdevils/css-selector-parser#40]
Doesn't Parse keyframe selectors?!

```css
@keyframes bounce {
  0%, 100% {
    transform: translateY(-25%);
    animation-timing-function: cubic-bezier(0.8,0,1,1);
  }

  50% {
    transform: none;
    animation-timing-function: cubic-bezier(0,0,0.2,1);
  }
}
```
```js
const parse = createParser();
const selector = parse('@keyframes bounce');
```
```
Error [ParserError]: css-selector-parser parse error: Expected rule but "@" found. Pos: 0.
```
```js
const parse = createParser();
const selector = parse('0%, 100%');
```
```
Error [ParserError]: css-selector-parser parse error: Expected rule but "0" found. Pos: 0.
```

Also  type in case of: `from`, `to`  will be parsed as   ` "type": "TagName"`
```css

@keyframes spin {
    from {
      transform: rotate(0deg);
    }
    to {
      transform: rotate(360deg);
    }
  }
```
