### ISSUE TITLE
Does it support The & nesting selector?

### ISSUE THREAD

**Issue by n4j1Br4ch1D** [mdevils/css-selector-parser#41]
Doesn't Parse The & nesting selector?!

```css
.parentClass {
    color: aqua;
    & .childClass {
      color:aquamarine;
    }
  }
 ```
```js

const parse = createParser();
const selector = parse('& .childClass');
```

```
Error [ParserError]: css-selector-parser parse error: Expected rule but "&" found. Pos: 0.
```
